### ISSUE TITLE
Improving demo templating maintainability

### ISSUE THREAD

**Issue by amtins** [SRGSSR/pillarbox-web#91]
**As Pillarbox maintainer**, I'd like to make templating management more developer-friendly, to make maintenance easier.

To achieve this, it would be interesting to investigate the following solutions:
- take advantage of [parceljs](https://parceljs.org/languages/html/#posthtml)/[posthtml](https://github.com/posthtml/posthtml)/[posthtml-include](https://github.com/posthtml/posthtml-include)
- using [web components](https://developer.mozilla.org/en-US/docs/Web/API/Web_components)
- html templates

Acceptance criteria

- select the most sustainable approach

**Comment by jboix** [comment]
After testing and investigating the different technologies listed above here are some feedback I've gathered :

**PostHTML:**
- Integrated templating framework within Parcel.
- Designed for compile-time use, and dynamic templating is limited.
- Possible to use PostHTML at runtime, but other solutions like Handlebars may be more suitable.
  
**Web Components:**
- Suitable solution, but templating is more focused on interpolation rather than bundling HTML files.
- Integrating a lightweight framework like Lit reduces the learning curve significantly.

**HTML Template:**
- Handlebars is commonly used for HTML templating.
- Templates need precompilation for performance.
- Parcel supports precompilation with plugins (not officially provided by parcel), but availability and maintenance may vary.
